export const tier2Words = [
  { id: 'abandon', en: 'Abandon', ru: 'бросать, оставлять', zh: '放弃' },
  { id: 'abstract', en: 'Abstract', ru: 'абстрактный', zh: '抽象的' },
  { id: 'academy', en: 'Academy', ru: 'академия', zh: '学院' },
  { id: 'access', en: 'Access', ru: 'доступ', zh: '访问' },
  { id: 'accommodate', en: 'Accommodate', ru: 'размещать, приспосабливать', zh: '容纳' },
  { id: 'accompany', en: 'Accompany', ru: 'сопровождать', zh: '陪伴' },
  { id: 'accumulate', en: 'Accumulate', ru: 'накапливать', zh: '积累' },
  { id: 'accurate', en: 'Accurate', ru: 'точный', zh: '准确的' },
  { id: 'achieve', en: 'Achieve', ru: 'достигать', zh: '实现' },
  { id: 'acknowledge', en: 'Acknowledge', ru: 'признавать', zh: '承认' },
  { id: 'acquire', en: 'Acquire', ru: 'приобретать', zh: '获得' },
  { id: 'adapt', en: 'Adapt', ru: 'адаптировать', zh: '适应' },
  { id: 'adequate', en: 'Adequate', ru: 'адекватный, достаточный', zh: '足够的' },
  { id: 'adjacent', en: 'Adjacent', ru: 'прилегающий', zh: '相邻的' },
  { id: 'adjust', en: 'Adjust', ru: 'регулировать, настраивать', zh: '调整' },
  { id: 'administrate', en: 'Administrate', ru: 'управлять', zh: '管理' },
  { id: 'adult', en: 'Adult', ru: 'взрослый', zh: '成年人' },
  { id: 'advocate', en: 'Advocate', ru: 'защищать (идею), выступать за', zh: '倡导' },
  { id: 'affect', en: 'Affect', ru: 'влиять', zh: '影响' },
  { id: 'aggregate', en: 'Aggregate', ru: 'совокупный', zh: '总计' },
  { id: 'aid', en: 'Aid', ru: 'помощь', zh: '援助' },
  { id: 'albeit', en: 'Albeit', ru: 'хотя и', zh: '尽管' },
  { id: 'allocate', en: 'Allocate', ru: 'распределять (ресурсы)', zh: '分配' },
  { id: 'alter', en: 'Alter', ru: 'изменять', zh: '改变' },
  { id: 'alternative', en: 'Alternative', ru: 'альтернатива', zh: '替代' },
  { id: 'ambiguous', en: 'Ambiguous', ru: 'двусмысленный', zh: '模棱两可的' },
  { id: 'amend', en: 'Amend', ru: 'вносить правки', zh: '修改' },
  { id: 'analogy', en: 'Analogy', ru: 'аналогия', zh: '类比' },
  { id: 'analyse', en: 'Analyse', ru: 'анализировать', zh: '分析' },
  { id: 'annual', en: 'Annual', ru: 'ежегодный', zh: '年度的' },
  { id: 'anticipate', en: 'Anticipate', ru: 'ожидать, предвидеть', zh: '预期' },
  { id: 'apparent', en: 'Apparent', ru: 'очевидный', zh: '明显的' },
  { id: 'append', en: 'Append', ru: 'добавлять', zh: '附加' },
  { id: 'appreciate', en: 'Appreciate', ru: 'ценить', zh: '欣赏' },
  { id: 'approach', en: 'Approach', ru: 'подход', zh: '方法' },
  { id: 'appropriate', en: 'Appropriate', ru: 'соответствующий', zh: '适当的' },
  { id: 'approximate', en: 'Approximate', ru: 'приблизительный', zh: '近似的' },
  { id: 'arbitrary', en: 'Arbitrary', ru: 'произвольный', zh: '任意的' },
  { id: 'area', en: 'Area', ru: 'область', zh: '区域' },
  { id: 'aspect', en: 'Aspect', ru: 'аспект', zh: '方面' },
  { id: 'assemble', en: 'Assemble', ru: 'собирать (вместе)', zh: '组装' },
  { id: 'assess', en: 'Assess', ru: 'оценивать', zh: '评估' },
  { id: 'assign', en: 'Assign', ru: 'назначать', zh: '分配' },
  { id: 'assist', en: 'Assist', ru: 'помогать', zh: '协助' },
  { id: 'assume', en: 'Assume', ru: 'предполагать', zh: '假设' },
  { id: 'assure', en: 'Assure', ru: 'уверять', zh: '保证' },
  { id: 'attach', en: 'Attach', ru: 'прикреплять', zh: '附上' },
  { id: 'attain', en: 'Attain', ru: 'достигать', zh: '达到' },
  { id: 'attitude', en: 'Attitude', ru: 'отношение', zh: '态度' },
  { id: 'attribute', en: 'Attribute', ru: 'свойство / приписывать', zh: '属性' },
  { id: 'author', en: 'Author', ru: 'автор', zh: '作者' },
  { id: 'authority', en: 'Authority', ru: 'власть, авторитет', zh: '权威' },
  { id: 'automate', en: 'Automate', ru: 'автоматизировать', zh: '自动化' },
  { id: 'available', en: 'Available', ru: 'доступный', zh: '可用的' },
  { id: 'aware', en: 'Aware', ru: 'осведомленный', zh: '意识到' },
  { id: 'behalf', en: 'Behalf', ru: 'от имени (кого-то)', zh: '代表' },
  { id: 'benefit', en: 'Benefit', ru: 'выгода', zh: '利益' },
  { id: 'bias', en: 'Bias', ru: 'предвзятость', zh: '偏见' },
  { id: 'bond', en: 'Bond', ru: 'связь, облигация', zh: '纽带' },
  { id: 'brief', en: 'Brief', ru: 'краткий', zh: '简短的' },
  { id: 'bulk', en: 'Bulk', ru: 'масса, основной объем', zh: '大量' },
  { id: 'capable', en: 'Capable', ru: 'способный', zh: '有能力的' },
  { id: 'capacity', en: 'Capacity', ru: 'вместимость, мощность', zh: '容量' },
  { id: 'category', en: 'Category', ru: 'категория', zh: '类别' },
  { id: 'cease', en: 'Cease', ru: 'прекращать', zh: '停止' },
  { id: 'challenge', en: 'Challenge', ru: 'вызов', zh: '挑战' },
  { id: 'channel', en: 'Channel', ru: 'канал', zh: '渠道' },
  { id: 'chapter', en: 'Chapter', ru: 'глава', zh: '章节' },
  { id: 'chart', en: 'Chart', ru: 'диаграмма, график', zh: '图表' },
  { id: 'chemical', en: 'Chemical', ru: 'химический', zh: '化学的' },
  { id: 'circumstance', en: 'Circumstance', ru: 'обстоятельство', zh: '情况' },
  { id: 'cite', en: 'Cite', ru: 'цитировать', zh: '引用' },
  { id: 'civil', en: 'Civil', ru: 'гражданский', zh: '民用的' },
  { id: 'clarify', en: 'Clarify', ru: 'прояснять', zh: '澄清' },
  { id: 'classic', en: 'Classic', ru: 'классический', zh: '经典的' },
  { id: 'clause', en: 'Clause', ru: 'пункт (договора), предложение', zh: '条款' },
  { id: 'code', en: 'Code', ru: 'код, кодекс', zh: '代码' },
  { id: 'coherent', en: 'Coherent', ru: 'связный, последовательный', zh: '连贯的' },
  { id: 'coincide', en: 'Coincide', ru: 'совпадать', zh: '一致' },
  { id: 'collapse', en: 'Collapse', ru: 'рухнуть', zh: '崩溃' },
  { id: 'colleague', en: 'Colleague', ru: 'коллега', zh: '同事' },
  { id: 'commence', en: 'Commence', ru: 'начинать', zh: '开始' },
  { id: 'comment', en: 'Comment', ru: 'комментарий', zh: '评论' },
  { id: 'commission', en: 'Commission', ru: 'комиссия', zh: '委员会' },
  { id: 'commit', en: 'Commit', ru: 'совершать, обязываться', zh: '承诺' },
  { id: 'commodity', en: 'Commodity', ru: 'товар', zh: '商品' },
  { id: 'communicate', en: 'Communicate', ru: 'общаться', zh: '沟通' },
  { id: 'community', en: 'Community', ru: 'сообщество', zh: '社区' },
  { id: 'compatible', en: 'Compatible', ru: 'совместимый', zh: '兼容的' },
  { id: 'compensate', en: 'Compensate', ru: 'компенсировать', zh: '补偿' },
  { id: 'compile', en: 'Compile', ru: 'компилировать, собирать', zh: '编译' },
  { id: 'complement', en: 'Complement', ru: 'дополнять', zh: '补充' },
  { id: 'complex', en: 'Complex', ru: 'сложный', zh: '复杂的' },
  { id: 'component', en: 'Component', ru: 'компонент', zh: '组件' },
  { id: 'compound', en: 'Compound', ru: 'соединение', zh: '化合物' },
  { id: 'comprehensive', en: 'Comprehensive', ru: 'всесторонний', zh: '全面的' },
  { id: 'comprise', en: 'Comprise', ru: 'включать, охватывать', zh: '包含' },
  { id: 'compute', en: 'Compute', ru: 'вычислять', zh: '计算' },
  { id: 'conceive', en: 'Conceive', ru: 'замышлять, понимать', zh: '构想' }
];

export default tier2Words;
